import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from fpdf import FPDF
from datetime import datetime
import os
import time
from database import get_db_connection

class DyslexiaPDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 24)
        self.set_text_color(102, 0, 204)
        self.cell(0, 10, 'CogniDetect', 0, 1, 'C')
        self.set_font('Arial', 'B', 14)
        self.set_text_color(50, 50, 50)
        self.cell(0, 10, 'Dyslexia Screening & Risk Assessment', 0, 1, 'C')
        self.set_draw_color(102, 0, 204)
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} - Generated by CogniDetect AI', 0, 0, 'C')

def get_interpretation(score, test_type):
    if test_type == 'phonology':
        if score >= 4: return "Normal / High Awareness"
        if score == 3: return "Mild Phonological Deficit"
        return "Significant Deficit (High Risk)"
    if test_type == 'reading':
        if score < 30: return "Normal Reading Flow"
        if score < 60: return "Moderate Regression Rate"
        return "High Regression / Disrupted Flow"
    if test_type == 'writing':
        if score < 30: return "Stable Handwriting"
        if score < 60: return "Minor Instability Detected"
        return "Dysgraphia Indicators Present"
    return "N/A"

def generate_dyslexia_chart(df, patient_name):
    if df.empty: return None
    dates = pd.to_datetime(df['timestamp'])
    scores = df['risk_score']
    
    plt.figure(figsize=(10, 4))
    plt.ylim(0, 105)
    plt.plot(dates, scores, marker='o', linestyle='-', color='#6600cc', label='Dyslexia Risk', linewidth=2)
    plt.axhline(y=60, color='orange', linestyle='--', label='Threshold (60%)')
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d'))
    plt.gcf().autofmt_xdate()
    plt.title(f"Risk Progression: {patient_name}")
    plt.ylabel("Risk (%)")
    plt.grid(True, linestyle='--', alpha=0.3)
    plt.legend()
    plt.tight_layout()
    
    chart_filename = f"temp_dyslexia_chart_{datetime.now().timestamp()}.png"
    plt.savefig(chart_filename)
    plt.close()
    return chart_filename

def create_dyslexia_report(patient_name):
    # 1. Wait to ensure DB consistency
    time.sleep(1.0)
    
    conn = get_db_connection()
    # Use dictionary cursor
    cursor = conn.cursor(dictionary=True)
    
    # 2. GET LATEST *DYSLEXIA* RECORD (The Fix)
    # We added: AND notes LIKE '%Dyslexia%'
    query_latest = """
        SELECT risk_score, phonology_score, reading_score, writing_score, timestamp 
        FROM patient_history 
        WHERE patient_name = %s AND notes LIKE '%%Dyslexia%%'
        ORDER BY timestamp DESC LIMIT 1
    """
    cursor.execute(query_latest, (patient_name,))
    record = cursor.fetchone()
    
    # 3. Get History for Chart
    query_history = """
        SELECT risk_score, timestamp 
        FROM patient_history 
        WHERE patient_name = %s AND notes LIKE '%%Dyslexia%%'
        ORDER BY timestamp ASC
    """
    history_df = pd.read_sql(query_history, conn, params=(patient_name,))
    
    cursor.close()
    conn.close()

    if not record:
        print(f"No Dyslexia records found for {patient_name}")
        return None

    # 4. Extract Data Safely
    overall_risk = record.get('risk_score') or 0
    p_score = record.get('phonology_score') or 0
    r_score = record.get('reading_score') or 0
    w_score = record.get('writing_score') or 0

    # 5. Build PDF
    pdf = DyslexiaPDF()
    pdf.add_page()

    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 10, f'Date: {datetime.now().strftime("%Y-%m-%d")}', 0, 1, 'R')
    pdf.cell(0, 10, f'Patient Name: {patient_name}', 0, 1, 'L')
    pdf.ln(5)

    # Breakdown Table
    pdf.set_fill_color(240, 230, 255)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, '  Clinical Breakdown', 0, 1, 'L', 1)
    pdf.ln(2)

    pdf.set_font('Arial', 'B', 11)
    pdf.cell(90, 10, 'Test Module', 1, 0, 'C')
    pdf.cell(40, 10, 'Score', 1, 0, 'C')
    pdf.cell(60, 10, 'Clinical Interpretation', 1, 1, 'C')

    pdf.set_font('Arial', '', 11)
    
    pdf.cell(90, 10, ' Phonological Awareness', 1, 0, 'L')
    pdf.cell(40, 10, f" {int(p_score)} / 5", 1, 0, 'C')
    pdf.cell(60, 10, f" {get_interpretation(p_score, 'phonology')}", 1, 1, 'L')

    pdf.cell(90, 10, ' Reading Flow', 1, 0, 'L')
    pdf.cell(40, 10, f" {int(r_score)} % Risk", 1, 0, 'C')
    pdf.cell(60, 10, f" {get_interpretation(r_score, 'reading')}", 1, 1, 'L')

    pdf.cell(90, 10, ' Dysgraphia (Writing)', 1, 0, 'L')
    pdf.cell(40, 10, f" {int(w_score)} % Risk", 1, 0, 'C')
    pdf.cell(60, 10, f" {get_interpretation(w_score, 'writing')}", 1, 1, 'L')
    pdf.ln(10)

    # Overall Risk
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, '  Overall Assessment', 0, 1, 'L', 1)
    pdf.ln(5)
    
    pdf.set_font('Arial', 'B', 30)
    if overall_risk < 30:
        pdf.set_text_color(0, 150, 0)
        status = "LOW RISK"
    elif overall_risk < 60:
        pdf.set_text_color(255, 140, 0)
        status = "MODERATE RISK"
    else:
        pdf.set_text_color(200, 0, 0)
        status = "HIGH DYSLEXIA RISK"
    
    pdf.cell(0, 15, f"{status} ({int(overall_risk)}%)", 0, 1, 'C')
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    # Chart
    chart_file = generate_dyslexia_chart(history_df, patient_name)
    if chart_file:
        try:
            pdf.image(chart_file, x=15, w=180)
            os.remove(chart_file)
        except: pass

    # Recommendation
    pdf.ln(5)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, "Recommendation:", 0, 1, 'L')
    pdf.set_font('Arial', '', 11)
    
    if overall_risk > 60:
        rec = "Significant indicators of dyslexia present. Formal evaluation recommended."
    elif overall_risk > 30:
        rec = "Mild indicators. Monitor progress and retest in 3 months."
    else:
        rec = "No significant indicators found."
        
    pdf.multi_cell(0, 7, rec, border=1)

    output_path = f"report_dyslexia_{patient_name.replace(' ', '_')}.pdf"
    pdf.output(output_path)
    return output_path